// src/templates/litigation/index.js
// Level-2 Litigation Template Engine (ESM)

export function buildLitigationTemplate({ caseId, creditor, facts, violations, persona = "paralegal" }) {
  return {
    templateType: "litigation_packet_v2",
    caseId,
    creditor,
    persona,
    draft: `
# Draft Litigation Packet — Case ${caseId}

Creditor: ${creditor}
Persona: ${persona}

## Statement of Facts
${facts || "No facts provided yet."}

## Alleged Violations
${Array.isArray(violations) ? violations.map((v) => "- " + v).join("\n") : "No violations listed."}

## Recommended Attachments
- Validation Demand
- Notice of Fault & Opportunity to Cure
- Evidence Packet
- Slack Timeline Extract
- AI Risk Forecast

This is an autogenerated template bundle (Level-2 Paralegal OS).
`,
  };
}

export function buildValidationNotice({ caseId, creditor }) {
  return {
    templateType: "validation_notice",
    caseId,
    creditor,
    draft: `
# Debt Validation Demand — Case ${caseId}

To: ${creditor}

This is a formal request for validation pursuant to the Fair Debt Collection Practices Act.
Provide verification of:
1. The original contract
2. Chain of title
3. Accounting ledger
4. Authority to collect

Failure to respond within 30 days will result in an Opportunity to Cure and escalation.

Autonomous Paralegal OS — Level 2
`,
  };
}

export function buildNoticeOfFault({ caseId, creditor }) {
  return {
    templateType: "notice_of_fault",
    caseId,
    creditor,
    draft: `
# Notice of Fault & Opportunity to Cure — Case ${caseId}

To: ${creditor}

You failed to provide validation or rebut the affidavit of facts.
This notifies you that you are now in fault and have 10 days to cure.

If no cure occurs:
- The matter proceeds to default.
- Enforcement packet is generated.
- Timeline escalates.

Autonomous Paralegal OS — Level 2
`,
  };
}

export const LitigationTemplates = {
  buildLitigationTemplate,
  buildValidationNotice,
  buildNoticeOfFault,
};

// Boot-safe minimal pack (supports common import styles)
export const litigationTemplates = {
  complaint: ({ facts = "" } = {}) => `COMPLAINT (Draft)\n\n${facts}\n`,
  motion: ({ title = "MOTION", facts = "" } = {}) => `${title}\n\n${facts}\n`,
  notice: ({ title = "NOTICE", facts = "" } = {}) => `${title}\n\n${facts}\n`,
  ...LitigationTemplates,
};

// Compatibility bridge to Litigation Engine v1 (registry/selector/renderer).
// Does not change the default export shape; it just exposes new entrypoints for
// code that still imports from src/templates/litigation.
export {
  buildLitigationPackage,
  renderLitigationDocument,
  buildMissingTemplateStub,
  buildBinderCoverAndIndex,
  getLitigationTemplatePlan,
  selectTemplateCandidates,
  normalizeVenue,
  normalizeCourtDivision,
} from "../../litigation/index.js";

// Support default imports: import litigationTemplates from ".../templates/litigation/index.js"
export default litigationTemplates;
