import { eventBus } from "../core/eventBus.js";
import fs from "node:fs/promises";
import path from "node:path";

const OUTPUT_DIR = path.resolve(process.cwd(), "output/docs");

async function ensureDir() {
  await fs.mkdir(OUTPUT_DIR, { recursive: true });
}

function sanitize(str = "") {
  return String(str || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

async function saveDraft(type, creditor, body) {
  await ensureDir();
  const filename = `${Date.now()}-${type}-${sanitize(creditor)}.txt`;
  const filepath = path.join(OUTPUT_DIR, filename);
  await fs.writeFile(filepath, body, "utf8");
  return filepath;
}

function buildNoticeOfFault({ creditor, accountRef }) {
  // NOTE: This is a *placeholder* scaffold. Replace with your real approved template language.
  return [
    "ISIAH TARIK HOWARD TRUST",
    "c/o Trustee",
    "",
    "RE: NOTICE OF FAULT AND OPPORTUNITY TO CURE",
    `Creditor: ${creditor}`,
    `Account/Reference: ${accountRef || "[Insert Reference]"}`,
    "",
    "SUMMARY:",
    "This is a draft Notice of Fault generated by SintraPrime Autonomous Mode.",
    "",
    "[Insert your full approved template language here...]",
    "",
    "Respectfully,",
    "Isiah-Tarik: Howard, Trustee",
    "",
  ].join("\n");
}

function buildDebtValidation({ creditor, classification }) {
  // NOTE: This is a *placeholder* scaffold. Replace with your real approved template language.
  return [
    "ISIAH TARIK HOWARD TRUST",
    "c/o Trustee",
    "",
    "RE: CONDITIONAL DEBT VALIDATION DEMAND",
    `Entity: ${creditor}`,
    `Classification: ${classification?.type || "unknown"} (${classification?.risk || "unknown"})`,
    "",
    "SUMMARY:",
    "This is a draft debt validation / standing challenge generated by SintraPrime.",
    "",
    "[Insert your full approved template language here...]",
    "",
    "Respectfully,",
    "Isiah-Tarik: Howard, Trustee",
    "",
  ].join("\n");
}

// Prevent duplicate drafts within a single process.
const recentDraftKeys = new Map();
const dedupeWindowMs = 60 * 60 * 1000; // 1h

function shouldDedupe(key) {
  const k = String(key || "").trim();
  if (!k) return false;

  const now = Date.now();
  for (const [rk, ts] of recentDraftKeys.entries()) {
    if (now - ts > dedupeWindowMs) recentDraftKeys.delete(rk);
  }

  if (recentDraftKeys.has(k)) return true;
  recentDraftKeys.set(k, now);
  return false;
}

// Overdue enforcement → Notice of Fault draft
eventBus.on("enforcement.overdue", async ({ creditor, accountRef, channel } = {}) => {
  const c = String(creditor || "").trim();
  if (!c) return;

  const dedupeKey = `notice_of_fault:${c}:${String(accountRef || "")}`;
  if (shouldDedupe(dedupeKey)) return;

  const draft = buildNoticeOfFault({ creditor: c, accountRef });
  const filepath = await saveDraft("notice-of-fault", c, draft);

  eventBus.emit("doc.generated", {
    type: "notice_of_fault",
    creditor: c,
    filepath,
    channel: channel || null,
  });
});

// Explicit doc request events (for playbooks)
eventBus.on("doc.generate.noticeOfFault", async ({ creditor, accountRef, channel } = {}) => {
  eventBus.emit("enforcement.overdue", { creditor, accountRef, channel });
});

// Junk debt buyer classification → DV letter draft
eventBus.on("creditor.classified", async (classification = {}) => {
  if (classification.tag !== "junk_debt_suspected") return;

  const creditor = String(classification.name || "").trim();
  if (!creditor) return;

  const dedupeKey = `debt_validation:${creditor}`;
  if (shouldDedupe(dedupeKey)) return;

  const draft = buildDebtValidation({ creditor, classification });
  const filepath = await saveDraft("debt-validation", creditor, draft);

  eventBus.emit("doc.generated", {
    type: "debt_validation",
    creditor,
    filepath,
    channel: classification?.context?.channel || null,
  });
});

eventBus.on("doc.generate.debtValidation", async ({ creditor, classification, channel } = {}) => {
  const c = String(creditor || "").trim();
  if (!c) return;

  const dedupeKey = `debt_validation:${c}`;
  if (shouldDedupe(dedupeKey)) return;

  const draft = buildDebtValidation({ creditor: c, classification: classification || {} });
  const filepath = await saveDraft("debt-validation", c, draft);

  eventBus.emit("doc.generated", {
    type: "debt_validation",
    creditor: c,
    filepath,
    channel: channel || null,
  });
});
