CREATE TABLE `document_verifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taxDocumentId` int NOT NULL,
	`verifiedBy` int NOT NULL,
	`verificationStatus` enum('verified','flagged','rejected') NOT NULL,
	`notes` text,
	`changesRequested` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `document_verifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `form1099_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taxDocumentId` int NOT NULL,
	`userId` int NOT NULL,
	`taxYear` int NOT NULL,
	`formType` varchar(20) NOT NULL,
	`payerName` varchar(500),
	`payerEIN` varchar(20),
	`recipientSSN` varchar(20),
	`recipientName` varchar(500),
	`interestIncome` int,
	`earlyWithdrawalPenalty` int,
	`interestOnUSSavingsBonds` int,
	`federalTaxWithheld` int,
	`ordinaryDividends` int,
	`qualifiedDividends` int,
	`capitalGainDistributions` int,
	`proceedsFromBroker` int,
	`costBasis` int,
	`grossDistribution` int,
	`taxableAmount` int,
	`distributionCode` varchar(10),
	`rawData` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `form1099_data_id` PRIMARY KEY(`id`),
	CONSTRAINT `form1099_data_taxDocumentId_unique` UNIQUE(`taxDocumentId`)
);
--> statement-breakpoint
CREATE TABLE `k1_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taxDocumentId` int NOT NULL,
	`userId` int NOT NULL,
	`taxYear` int NOT NULL,
	`formType` varchar(20) NOT NULL,
	`entityName` varchar(500),
	`entityEIN` varchar(20),
	`partnerSSN` varchar(20),
	`partnerName` varchar(500),
	`ordinaryBusinessIncome` int,
	`netRentalRealEstateIncome` int,
	`otherNetRentalIncome` int,
	`guaranteedPayments` int,
	`interestIncome` int,
	`ordinaryDividends` int,
	`qualifiedDividends` int,
	`royalties` int,
	`netShortTermCapitalGain` int,
	`netLongTermCapitalGain` int,
	`collectiblesGain` int,
	`section1231Gain` int,
	`otherIncome` int,
	`section179Deduction` int,
	`otherDeductions` int,
	`selfEmploymentEarnings` int,
	`rawData` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `k1_data_id` PRIMARY KEY(`id`),
	CONSTRAINT `k1_data_taxDocumentId_unique` UNIQUE(`taxDocumentId`)
);
--> statement-breakpoint
CREATE TABLE `tax_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fileName` varchar(500) NOT NULL,
	`fileUrl` text NOT NULL,
	`fileKey` text NOT NULL,
	`mimeType` varchar(100) NOT NULL,
	`documentType` varchar(100) NOT NULL,
	`taxYear` int,
	`status` enum('uploaded','processing','extracted','verified','failed') NOT NULL DEFAULT 'uploaded',
	`ocrText` text,
	`extractedData` json,
	`verificationStatus` enum('pending','verified','flagged') DEFAULT 'pending',
	`verificationNotes` text,
	`tags` json,
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`processedAt` timestamp,
	CONSTRAINT `tax_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `w2_data` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taxDocumentId` int NOT NULL,
	`userId` int NOT NULL,
	`taxYear` int NOT NULL,
	`employerName` varchar(500),
	`employerEIN` varchar(20),
	`employeeSSN` varchar(20),
	`employeeName` varchar(500),
	`wages` int,
	`federalTaxWithheld` int,
	`socialSecurityWages` int,
	`socialSecurityTaxWithheld` int,
	`medicareWages` int,
	`medicareTaxWithheld` int,
	`socialSecurityTips` int,
	`allocatedTips` int,
	`stateWages` int,
	`stateTaxWithheld` int,
	`state` varchar(2),
	`rawData` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `w2_data_id` PRIMARY KEY(`id`),
	CONSTRAINT `w2_data_taxDocumentId_unique` UNIQUE(`taxDocumentId`)
);
