CREATE TABLE `autonomous_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` varchar(255) NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`objective` text,
	`priority` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`status` enum('pending','running','completed','failed','queued') NOT NULL DEFAULT 'pending',
	`context` text,
	`assigned_agent_id` varchar(255),
	`execution_plan` json,
	`result` json,
	`ai_tokens_used` int,
	`execution_time_ms` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`started_at` timestamp,
	`completed_at` timestamp,
	`tags` json,
	CONSTRAINT `autonomous_tasks_id` PRIMARY KEY(`id`)
);
