/**
 * Seed Intelligence Database with 100 AI Tools
 * 
 * Run with: npx tsx scripts/seed-ai-tools.ts
 */

import { createAITool } from "../server/db";

const aiTools = [
  // === SCRIPT GENERATION (10 tools) ===
  {
    name: "ChatGPT",
    category: "script",
    description: "General-purpose AI for script writing, brainstorming, and content creation",
    reliabilityScore: 9,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Best for quick drafts and ideation. Requires editing for professional output.",
  },
  {
    name: "Claude",
    category: "script",
    description: "Long-form content generation with superior context handling",
    reliabilityScore: 9,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Excellent for legal briefs, research papers, and detailed scripts.",
  },
  {
    name: "Jasper AI",
    category: "script",
    description: "Marketing-focused copywriting and content generation",
    reliabilityScore: 7,
    budgetTier: "premium",
    skillLevel: "intermediate",
    notes: "Great for ads, landing pages, and marketing materials. Expensive.",
  },
  {
    name: "Copy.ai",
    category: "script",
    description: "Fast copywriting for social media, ads, and short-form content",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Good for quick social posts and ad copy. Limited long-form capabilities.",
  },
  {
    name: "Writesonic",
    category: "script",
    description: "AI writer for articles, blogs, and marketing copy",
    reliabilityScore: 6,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Affordable but quality varies. Good for volume content.",
  },
  {
    name: "Sudowrite",
    category: "script",
    description: "Creative fiction and storytelling AI",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Best for narrative scripts, novels, and creative writing.",
  },
  {
    name: "Rytr",
    category: "script",
    description: "Budget-friendly AI writing assistant",
    reliabilityScore: 6,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Good entry-level tool. Limited advanced features.",
  },
  {
    name: "Anyword",
    category: "script",
    description: "Data-driven copywriting with performance prediction",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Predicts ad performance. Expensive but ROI-focused.",
  },
  {
    name: "Frase",
    category: "script",
    description: "SEO-optimized content briefs and writing",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Great for SEO content. Includes research tools.",
  },
  {
    name: "Scalenut",
    category: "script",
    description: "AI-powered SEO and content marketing platform",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "All-in-one SEO content solution. Learning curve.",
  },

  // === IMAGE GENERATION (15 tools) ===
  {
    name: "Midjourney",
    category: "image",
    description: "Premium AI art generation with photorealistic and artistic styles",
    reliabilityScore: 10,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Industry standard for quality. Requires Discord. Prompt engineering essential.",
  },
  {
    name: "DALL-E 3",
    category: "image",
    description: "OpenAI's image generator with excellent text rendering",
    reliabilityScore: 9,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Best for images with text. Integrated with ChatGPT.",
  },
  {
    name: "Stable Diffusion",
    category: "image",
    description: "Open-source image generation with full control",
    reliabilityScore: 8,
    budgetTier: "free",
    skillLevel: "advanced",
    notes: "Free and customizable. Requires technical setup.",
  },
  {
    name: "Leonardo.ai",
    category: "image",
    description: "Game asset and character design AI",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Excellent for consistent character generation and game art.",
  },
  {
    name: "Firefly (Adobe)",
    category: "image",
    description: "Commercial-safe AI image generation integrated with Adobe suite",
    reliabilityScore: 9,
    budgetTier: "premium",
    skillLevel: "intermediate",
    notes: "Safe for commercial use. Seamless Adobe integration.",
  },
  {
    name: "Ideogram",
    category: "image",
    description: "AI image generator with superior text rendering",
    reliabilityScore: 8,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Best for logos, posters, and text-heavy images.",
  },
  {
    name: "Playground AI",
    category: "image",
    description: "Free AI image generation with generous limits",
    reliabilityScore: 7,
    budgetTier: "free",
    skillLevel: "beginner",
    notes: "Great for experimentation. Quality varies.",
  },
  {
    name: "Canva AI",
    category: "image",
    description: "Integrated AI image generation in Canva design platform",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Convenient for quick designs. Limited customization.",
  },
  {
    name: "Photoshop AI (Generative Fill)",
    category: "image",
    description: "AI-powered image editing and generation in Photoshop",
    reliabilityScore: 9,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Professional-grade editing. Requires Photoshop subscription.",
  },
  {
    name: "Runway Gen-2",
    category: "image",
    description: "AI image and video generation with advanced controls",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Cutting-edge features. Expensive for high volume.",
  },
  {
    name: "NightCafe",
    category: "image",
    description: "Community-driven AI art platform with multiple models",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Good for artistic styles. Active community.",
  },
  {
    name: "Artbreeder",
    category: "image",
    description: "Collaborative AI art creation with genetic algorithms",
    reliabilityScore: 6,
    budgetTier: "free",
    skillLevel: "beginner",
    notes: "Unique blending approach. Limited control.",
  },
  {
    name: "DreamStudio",
    category: "image",
    description: "Official Stable Diffusion interface with credits system",
    reliabilityScore: 8,
    budgetTier: "low",
    skillLevel: "intermediate",
    notes: "Stable Diffusion with user-friendly interface.",
  },
  {
    name: "Craiyon (DALL-E mini)",
    category: "image",
    description: "Free AI image generation for quick concepts",
    reliabilityScore: 5,
    budgetTier: "free",
    skillLevel: "beginner",
    notes: "Low quality but completely free. Good for rough ideas.",
  },
  {
    name: "BlueWillow",
    category: "image",
    description: "Free Midjourney alternative on Discord",
    reliabilityScore: 6,
    budgetTier: "free",
    skillLevel: "beginner",
    notes: "Decent quality for free. Slower than Midjourney.",
  },

  // === VIDEO GENERATION (12 tools) ===
  {
    name: "Runway Gen-3",
    category: "video",
    description: "Text-to-video and image-to-video AI generation",
    reliabilityScore: 9,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Industry-leading video quality. Expensive.",
  },
  {
    name: "Pika Labs",
    category: "video",
    description: "AI video generation from text and images",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Good quality-to-cost ratio. Discord-based.",
  },
  {
    name: "InVideo AI",
    category: "video",
    description: "Script-to-video with stock footage and voiceover",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Best for YouTube videos and marketing content.",
  },
  {
    name: "Synthesia",
    category: "video",
    description: "AI avatar video generation with text-to-speech",
    reliabilityScore: 9,
    budgetTier: "premium",
    skillLevel: "beginner",
    notes: "Professional avatars. Great for training videos.",
  },
  {
    name: "HeyGen",
    category: "video",
    description: "AI spokesperson videos with realistic avatars",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Affordable avatar videos. Good for marketing.",
  },
  {
    name: "Pictory",
    category: "video",
    description: "Article-to-video and script-to-video conversion",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Fast video creation from text. Limited customization.",
  },
  {
    name: "Descript",
    category: "video",
    description: "Video editing through text transcripts with AI features",
    reliabilityScore: 9,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Revolutionary editing workflow. Excellent for podcasts.",
  },
  {
    name: "Fliki",
    category: "video",
    description: "Text-to-video with AI voices and stock media",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Budget-friendly. Good for social media videos.",
  },
  {
    name: "Lumen5",
    category: "video",
    description: "Blog-to-video conversion with AI",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Repurpose written content into videos. Template-based.",
  },
  {
    name: "Kapwing",
    category: "video",
    description: "Online video editor with AI subtitle and editing tools",
    reliabilityScore: 8,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "User-friendly. Good for quick edits.",
  },
  {
    name: "Opus Clip",
    category: "video",
    description: "AI-powered long-form to short-form video conversion",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Excellent for repurposing podcasts into clips.",
  },
  {
    name: "Wondershare Filmora",
    category: "video",
    description: "Video editing software with AI features",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Traditional editor with AI enhancements.",
  },

  // === AUDIO & VOICE (10 tools) ===
  {
    name: "ElevenLabs",
    category: "audio",
    description: "Photorealistic voice cloning and text-to-speech",
    reliabilityScore: 10,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Best-in-class voice quality. Industry standard.",
  },
  {
    name: "Murf AI",
    category: "audio",
    description: "Professional voiceover generation with 120+ voices",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Good voice variety. Commercial license included.",
  },
  {
    name: "Play.ht",
    category: "audio",
    description: "Realistic text-to-speech with voice cloning",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Affordable voice cloning. Good quality.",
  },
  {
    name: "Speechify",
    category: "audio",
    description: "Text-to-speech for reading articles and documents",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Great for accessibility. Mobile-friendly.",
  },
  {
    name: "Descript Overdub",
    category: "audio",
    description: "Voice cloning for podcast editing",
    reliabilityScore: 9,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Seamless integration with Descript editor.",
  },
  {
    name: "Resemble AI",
    category: "audio",
    description: "Real-time voice cloning and synthesis",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "API-first. Good for developers.",
  },
  {
    name: "AIVA",
    category: "audio",
    description: "AI music composition for videos and games",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Royalty-free music generation. Limited styles.",
  },
  {
    name: "Soundraw",
    category: "audio",
    description: "AI music generation with customization",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Easy music creation. Good for YouTube.",
  },
  {
    name: "Boomy",
    category: "audio",
    description: "Instant AI music creation and distribution",
    reliabilityScore: 6,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Quick music generation. Limited control.",
  },
  {
    name: "Adobe Podcast AI",
    category: "audio",
    description: "AI-powered audio enhancement and editing",
    reliabilityScore: 9,
    budgetTier: "free",
    skillLevel: "beginner",
    notes: "Excellent noise removal. Free tier available.",
  },

  // === AUTOMATION (12 tools) ===
  {
    name: "Make (Integromat)",
    category: "automation",
    description: "Visual automation platform with 1000+ integrations",
    reliabilityScore: 9,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "More powerful than Zapier. Steeper learning curve.",
  },
  {
    name: "Zapier",
    category: "automation",
    description: "No-code automation connecting 5000+ apps",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Easy to use. Can get expensive at scale.",
  },
  {
    name: "n8n",
    category: "automation",
    description: "Open-source workflow automation",
    reliabilityScore: 8,
    budgetTier: "free",
    skillLevel: "advanced",
    notes: "Self-hosted. Full control. Requires technical skills.",
  },
  {
    name: "Bardeen",
    category: "automation",
    description: "Browser automation with AI",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Great for web scraping. Limited to browser.",
  },
  {
    name: "Automate.io",
    category: "automation",
    description: "Simple automation platform for common workflows",
    reliabilityScore: 6,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Budget-friendly. Limited features.",
  },
  {
    name: "Integrately",
    category: "automation",
    description: "One-click automation with pre-built templates",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Fast setup. Good for simple workflows.",
  },
  {
    name: "Pipedream",
    category: "automation",
    description: "Developer-first automation with code",
    reliabilityScore: 8,
    budgetTier: "free",
    skillLevel: "advanced",
    notes: "Generous free tier. Requires coding.",
  },
  {
    name: "IFTTT",
    category: "automation",
    description: "Simple if-this-then-that automation",
    reliabilityScore: 6,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Very basic. Good for personal use.",
  },
  {
    name: "Workato",
    category: "automation",
    description: "Enterprise automation and integration platform",
    reliabilityScore: 9,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Enterprise-grade. Expensive.",
  },
  {
    name: "Tray.io",
    category: "automation",
    description: "Low-code automation for enterprises",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "intermediate",
    notes: "Powerful but pricey. Good for large teams.",
  },
  {
    name: "Microsoft Power Automate",
    category: "automation",
    description: "Automation within Microsoft ecosystem",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Best for Microsoft 365 users.",
  },
  {
    name: "Parabola",
    category: "automation",
    description: "Visual data workflow automation",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Great for data transformation. Niche use case.",
  },

  // === RESEARCH & ANALYSIS (15 tools) ===
  {
    name: "Perplexity AI",
    category: "research",
    description: "AI-powered search engine with citations",
    reliabilityScore: 9,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Best for research. Provides sources.",
  },
  {
    name: "Consensus",
    category: "research",
    description: "AI search for scientific research papers",
    reliabilityScore: 8,
    budgetTier: "low",
    skillLevel: "intermediate",
    notes: "Excellent for academic research.",
  },
  {
    name: "Elicit",
    category: "research",
    description: "AI research assistant for literature reviews",
    reliabilityScore: 8,
    budgetTier: "free",
    skillLevel: "intermediate",
    notes: "Summarizes research papers. Free tier available.",
  },
  {
    name: "Semantic Scholar",
    category: "research",
    description: "AI-powered academic search engine",
    reliabilityScore: 9,
    budgetTier: "free",
    skillLevel: "intermediate",
    notes: "Free and comprehensive. Academic focus.",
  },
  {
    name: "Scite",
    category: "research",
    description: "Citation analysis with AI",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "advanced",
    notes: "Shows how papers are cited. Valuable for research.",
  },
  {
    name: "Notion AI",
    category: "research",
    description: "AI writing and research within Notion",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Convenient for Notion users. Limited capabilities.",
  },
  {
    name: "Mem",
    category: "research",
    description: "AI-powered note-taking and knowledge management",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Smart organization. Niche audience.",
  },
  {
    name: "Otter.ai",
    category: "research",
    description: "AI meeting transcription and notes",
    reliabilityScore: 9,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Excellent for meetings and interviews.",
  },
  {
    name: "Fireflies.ai",
    category: "research",
    description: "AI meeting assistant with transcription",
    reliabilityScore: 8,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Good Zoom/Teams integration.",
  },
  {
    name: "Fathom",
    category: "research",
    description: "Free AI meeting notes and summaries",
    reliabilityScore: 7,
    budgetTier: "free",
    skillLevel: "beginner",
    notes: "Completely free. Good quality.",
  },
  {
    name: "ChatPDF",
    category: "research",
    description: "AI-powered PDF analysis and Q&A",
    reliabilityScore: 7,
    budgetTier: "free",
    skillLevel: "beginner",
    notes: "Quick PDF insights. Limited depth.",
  },
  {
    name: "Humata AI",
    category: "research",
    description: "AI for analyzing complex documents",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Good for legal and technical docs.",
  },
  {
    name: "Scholarcy",
    category: "research",
    description: "AI article summarizer for research",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Extracts key findings. Academic focus.",
  },
  {
    name: "Iris.ai",
    category: "research",
    description: "AI research workspace for scientists",
    reliabilityScore: 7,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Powerful but expensive. For serious researchers.",
  },
  {
    name: "ResearchRabbit",
    category: "research",
    description: "AI-powered paper discovery and visualization",
    reliabilityScore: 8,
    budgetTier: "free",
    skillLevel: "intermediate",
    notes: "Excellent for finding related papers. Free.",
  },

  // === LEGAL TECH (10 tools) ===
  {
    name: "Harvey AI",
    category: "legal",
    description: "AI legal assistant for law firms",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Enterprise legal AI. Expensive.",
  },
  {
    name: "CaseText (CoCounsel)",
    category: "legal",
    description: "AI legal research and document review",
    reliabilityScore: 9,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Industry-leading legal AI. High cost.",
  },
  {
    name: "Lexis+ AI",
    category: "legal",
    description: "LexisNexis AI legal research platform",
    reliabilityScore: 9,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Trusted brand. Enterprise pricing.",
  },
  {
    name: "Westlaw Precision",
    category: "legal",
    description: "Thomson Reuters AI legal research",
    reliabilityScore: 9,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Comprehensive legal database. Expensive.",
  },
  {
    name: "DoNotPay",
    category: "legal",
    description: "AI lawyer for consumer legal issues",
    reliabilityScore: 6,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Good for simple consumer issues. Limited scope.",
  },
  {
    name: "LegalZoom AI",
    category: "legal",
    description: "AI-assisted legal document creation",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Good for standard documents. Not for complex cases.",
  },
  {
    name: "Rocket Lawyer",
    category: "legal",
    description: "Online legal services with AI assistance",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Affordable legal documents. Basic AI features.",
  },
  {
    name: "Kira Systems",
    category: "legal",
    description: "AI contract analysis and due diligence",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Excellent for M&A. Enterprise tool.",
  },
  {
    name: "Luminance",
    category: "legal",
    description: "AI for contract review and negotiation",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Used by top law firms. Expensive.",
  },
  {
    name: "ROSS Intelligence",
    category: "legal",
    description: "AI legal research assistant",
    reliabilityScore: 7,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Natural language legal search. Niche tool.",
  },

  // === MARKETING & SOCIAL (16 tools) ===
  {
    name: "Buffer AI",
    category: "marketing",
    description: "AI-powered social media scheduling and analytics",
    reliabilityScore: 8,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Easy scheduling. Good analytics.",
  },
  {
    name: "Hootsuite AI",
    category: "marketing",
    description: "Social media management with AI content suggestions",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Comprehensive platform. Can be expensive.",
  },
  {
    name: "Lately AI",
    category: "marketing",
    description: "AI that converts long-form content into social posts",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "beginner",
    notes: "Good for content repurposing.",
  },
  {
    name: "Predis.ai",
    category: "marketing",
    description: "AI social media content generator with visuals",
    reliabilityScore: 7,
    budgetTier: "low",
    skillLevel: "beginner",
    notes: "Creates posts with images. Affordable.",
  },
  {
    name: "Brandwatch",
    category: "marketing",
    description: "AI-powered social listening and analytics",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Enterprise social intelligence. Expensive.",
  },
  {
    name: "Sprout Social",
    category: "marketing",
    description: "Social media management with AI insights",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "intermediate",
    notes: "Powerful analytics. High cost.",
  },
  {
    name: "Surfer SEO",
    category: "marketing",
    description: "AI-powered SEO content optimization",
    reliabilityScore: 8,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Data-driven SEO. Good ROI.",
  },
  {
    name: "Clearscope",
    category: "marketing",
    description: "AI content optimization for SEO",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "intermediate",
    notes: "High-quality SEO insights. Expensive.",
  },
  {
    name: "MarketMuse",
    category: "marketing",
    description: "AI content planning and optimization",
    reliabilityScore: 7,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Comprehensive content strategy. Enterprise pricing.",
  },
  {
    name: "Phrasee",
    category: "marketing",
    description: "AI copywriting for email and social ads",
    reliabilityScore: 7,
    budgetTier: "premium",
    skillLevel: "intermediate",
    notes: "Optimizes for conversions. Expensive.",
  },
  {
    name: "Persado",
    category: "marketing",
    description: "AI-generated marketing language",
    reliabilityScore: 7,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Enterprise marketing AI. Very expensive.",
  },
  {
    name: "Seventh Sense",
    category: "marketing",
    description: "AI email send time optimization",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Improves email open rates. Niche tool.",
  },
  {
    name: "Adext AI",
    category: "marketing",
    description: "AI-powered ad campaign optimization",
    reliabilityScore: 6,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Automates ad bidding. Mixed results.",
  },
  {
    name: "Pattern89",
    category: "marketing",
    description: "AI creative optimization for ads",
    reliabilityScore: 7,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Predicts ad performance. Enterprise tool.",
  },
  {
    name: "Smartly.io",
    category: "marketing",
    description: "AI-powered social advertising automation",
    reliabilityScore: 8,
    budgetTier: "premium",
    skillLevel: "advanced",
    notes: "Facebook/Instagram ad automation. Expensive.",
  },
  {
    name: "Pencil",
    category: "marketing",
    description: "AI ad creative generation and testing",
    reliabilityScore: 7,
    budgetTier: "medium",
    skillLevel: "intermediate",
    notes: "Generates ad variations. Good for testing.",
  },
];

async function seedAITools() {
  console.log("Starting AI Tools seeding...");
  
  for (const tool of aiTools) {
    try {
      await createAITool(tool);
      console.log(`✓ Seeded: ${tool.name}`);
    } catch (error) {
      console.error(`✗ Failed to seed ${tool.name}:`, error);
    }
  }
  
  console.log(`\n✅ Seeding complete! Added ${aiTools.length} AI tools to the database.`);
  console.log("\nCategory breakdown:");
  const categories = aiTools.reduce((acc: Record<string, number>, tool) => {
    acc[tool.category] = (acc[tool.category] || 0) + 1;
    return acc;
  }, {});
  
  Object.entries(categories).forEach(([category, count]) => {
    console.log(`  ${category}: ${count} tools`);
  });
  
  process.exit(0);
}

seedAITools().catch((error) => {
  console.error("Seeding failed:", error);
  process.exit(1);
});
