// src/intelligence/litigation/iracEngine.js
// Level 3 Litigation Engine — IRAC Core (template-only)
// NOTE: This is not legal advice; it is a formatting engine for internal drafting workflows.

function asStr(v) {
  return v == null ? "" : String(v);
}

export function runIRAC({ issue, rules, analysis, conclusion } = {}) {
  const rulesText = Array.isArray(rules) ? rules.map((r) => `- ${asStr(r)}`).join("\n") : asStr(rules);

  return `
# IRAC Analysis

## Issue
${asStr(issue).trim() || "Issue not provided"}

## Rules
${rulesText.trim() || "Rules not provided"}

## Analysis
${asStr(analysis).trim() || "Analysis placeholder"}

## Conclusion
${asStr(conclusion).trim() || "Conclusion placeholder"}

(Autogenerated via Litigation Engine L3)
`;
}

export function makeComplaintDraft({ facts = {}, causes = [], defendant, plaintiff, caseId } = {}) {
  const causeLines = Array.isArray(causes) ? causes.map((c, i) => `${i + 1}. ${asStr(c)}`).join("\n") : asStr(causes);

  return `
# Draft Complaint — Case ${asStr(caseId).trim() || "(unassigned)"}

Plaintiff: ${asStr(plaintiff).trim() || "(plaintiff pending)"}
Defendant: ${asStr(defendant).trim() || "(defendant pending)"}

## Jurisdiction
This court has jurisdiction because ${asStr(facts.jurisdiction).trim() || "jurisdictional details pending"}.

## Facts
${asStr(facts.summary).trim() || "Facts not provided"}

## Causes of Action
${causeLines.trim() || "Causes not provided"}

## Prayer for Relief
Plaintiff demands:
- Damages
- Injunctive relief
- Costs
- Any further relief deemed just

(Generated by Litigation Engine L3)
`;
}
